-- SQLite

-- Consultas
SELECT NAME, LASTNAME, EMAIL FROM CUSTOMERS WHERE STATE = 'SP';

SELECT * FROM CARS WHERE STATUS = 'Liberado';
SELECT * FROM CARS WHERE YEAR = '2016';

SELECT NAME, POSITION_ID, POSITIONS.DESCRIPTION FROM EMPLOYEES
INNER JOIN POSITIONS ON POSITIONS.ID = EMPLOYEES.POSITION_ID;

SELECT ID, NAME, LOCATIONS_COUNT FROM EMPLOYEES
INNER JOIN (
    SELECT EMPLOYEE_ID, COUNT(*) as LOCATIONS_COUNT 
    FROM LOCATIONS
    GROUP BY EMPLOYEE_ID
    HAVING LOCATIONS_COUNT >= 2
) AS withMoreThanTwoLocations ON EMPLOYEES.ID = withMoreThanTwoLocations.EMPLOYEE_ID;

SELECT ID, NAME, LOCATIONS_COUNT FROM CUSTOMERS
INNER JOIN (
    SELECT CUSTOMER_ID, COUNT(*) as LOCATIONS_COUNT
    FROM LOCATIONS
    GROUP BY CUSTOMER_ID
    HAVING LOCATIONS_COUNT >= 2
) AS withMoreThanTwoLocations ON CUSTOMERS.ID = withMoreThanTwoLocations.CUSTOMER_ID;