-- SQLite

-- Updates
UPDATE CUSTOMERS SET EMAIL = 'carolina@campuscode.com.br' WHERE ID = 9;
UPDATE CUSTOMERS SET BIRTH_DATE = '1986-06-19' WHERE ID = 4;

UPDATE CARS SET YEAR = 2019 WHERE ID = 4;

ALTER TABLE EMPLOYEES RENAME PHONE TO PHONE_NUMBER;

-- Deletes
DELETE FROM CARS WHERE NAME = 'Hyundai HB20 1.6';
